#!/usr/bin/env python3
"""Build a deterministic, non-mutating EDU-DATA-1 core identity proposal plan.

Input: staging_candidates.jsonl generated by build_staging_seed.py.
Output:
- core_identity_proposals.jsonl: canonical identity proposals only.
- identity_review_tasks.jsonl: ambiguous proposal groups requiring review.
- core_seed_plan_report.json: safety/accounting report.

This tool never writes to edu_core and never accepts identity matches automatically.
"""
from __future__ import annotations

import argparse
import json
import uuid
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

PLAN_NAMESPACE = uuid.UUID("1499d565-4a29-4c10-83ae-7a9fc7db7d9e")
SUPPORTED_IDENTITY_SOURCES = {"azhar_institute_guide", "scu_institutions"}


def load_jsonl(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, 1):
            if not line.strip():
                continue
            try:
                value = json.loads(line)
            except json.JSONDecodeError as exc:
                raise SystemExit(f"{path}:{line_no}: invalid JSON: {exc}") from exc
            if not isinstance(value, dict):
                raise SystemExit(f"{path}:{line_no}: expected JSON object")
            rows.append(value)
    return rows


def official_current_candidate(candidate: dict) -> bool:
    features = candidate.get("match_features") or {}
    authority = str(features.get("authority_class") or "")
    return (
        candidate.get("candidate_status") == "ready"
        and features.get("coverage_credit") == "current"
        and authority.startswith("primary_")
        and features.get("registry_source_id") in SUPPORTED_IDENTITY_SOURCES
    )


def identity_key(candidate: dict) -> tuple[str | None, str | None]:
    """Return (identity_key, missing_reason).

    Keys are proposal keys, not durable public IDs. They are deterministic only
    so repeated planning runs can be compared safely.
    """
    features = candidate.get("match_features") or {}
    registry_source_id = features.get("registry_source_id")
    if registry_source_id == "azhar_institute_guide":
        official_identifier = str(candidate.get("official_identifier") or "").strip()
        if not official_identifier:
            return None, "azhar_missing_official_identifier"
        return f"azhar_institute_guide:{official_identifier}", None

    if registry_source_id == "scu_institutions":
        normalized_name = candidate.get("normalized_name_ar") or candidate.get("normalized_name_en")
        if not normalized_name:
            return None, "scu_missing_normalized_name"
        normalized_type = candidate.get("normalized_type") or candidate.get("entity_type_raw") or "unknown"
        return f"scu_institutions:{normalized_type}:{normalized_name}", None

    return None, "unsupported_registry_source"


def first_nonempty(rows: list[dict], field: str):
    for row in rows:
        value = row.get(field)
        if value not in (None, ""):
            return value
    return None


def proposal_for_group(key: str, rows: list[dict]) -> tuple[dict, dict | None]:
    rows = sorted(rows, key=lambda item: (int(item.get("raw_id") or 0), str(item.get("source_record_id") or "")))
    features = rows[0].get("match_features") or {}
    registry_source_id = features.get("registry_source_id")

    names_ar = sorted({str(r["name_ar"]).strip() for r in rows if r.get("name_ar")})
    names_en = sorted({str(r["name_en"]).strip() for r in rows if r.get("name_en")})
    source_record_ids = [r.get("source_record_id") for r in rows if r.get("source_record_id") is not None]
    raw_ids = [int(r["raw_id"]) for r in rows]

    review_reasons: list[str] = []
    if registry_source_id == "azhar_institute_guide" and len(rows) > 1:
        review_reasons.append("duplicate_azhar_official_identifier")
    if registry_source_id == "scu_institutions" and len(rows) > 1:
        review_reasons.append("duplicate_scu_normalized_identity")
    if len(names_ar) > 1:
        review_reasons.append("conflicting_arabic_names")
    if len(names_en) > 1:
        review_reasons.append("conflicting_english_names")

    proposal = {
        "proposal_id": str(uuid.uuid5(PLAN_NAMESPACE, key)),
        "proposal_key": key,
        "registry_source_id": registry_source_id,
        "entity_family": first_nonempty(rows, "entity_family"),
        "institution_type": first_nonempty(rows, "normalized_type") or first_nonempty(rows, "entity_type_raw"),
        "candidate_name_ar": names_ar[0] if len(names_ar) == 1 else None,
        "candidate_name_en": names_en[0] if len(names_en) == 1 else None,
        "name_ar_options": names_ar,
        "name_en_options": names_en,
        "raw_ids": raw_ids,
        "source_record_ids": source_record_ids,
        "evidence_count": len(rows),
        "decision": "needs_review" if review_reasons else "unreviewed",
        "review_reasons": review_reasons,
        "automatic_acceptance": False,
        "core_mutation_allowed": False,
    }

    review_task = None
    if review_reasons:
        review_task = {
            "task_type": "identity_match",
            "proposal_id": proposal["proposal_id"],
            "proposal_key": key,
            "registry_source_id": registry_source_id,
            "raw_ids": raw_ids,
            "source_record_ids": source_record_ids,
            "reasons": review_reasons,
            "status": "open",
        }
    return proposal, review_task


def build_plan(candidates: list[dict]) -> tuple[list[dict], list[dict], dict]:
    grouped: dict[str, list[dict]] = defaultdict(list)
    ignored = Counter()
    missing_key = Counter()
    source_rows = Counter()

    for candidate in candidates:
        features = candidate.get("match_features") or {}
        registry_source_id = features.get("registry_source_id") or "unmapped"

        if not official_current_candidate(candidate):
            if candidate.get("candidate_status") != "ready":
                ignored["candidate_not_ready"] += 1
            elif features.get("coverage_credit") != "current":
                ignored["not_current_coverage"] += 1
            elif not str(features.get("authority_class") or "").startswith("primary_"):
                ignored["not_primary_authority"] += 1
            else:
                ignored["unsupported_registry_source"] += 1
            continue

        source_rows[registry_source_id] += 1
        key, reason = identity_key(candidate)
        if not key:
            missing_key[reason or "missing_identity_key"] += 1
            continue
        grouped[key].append(candidate)

    proposals: list[dict] = []
    review_tasks: list[dict] = []
    for key in sorted(grouped):
        proposal, review_task = proposal_for_group(key, grouped[key])
        proposals.append(proposal)
        if review_task:
            review_tasks.append(review_task)

    proposals_by_source = Counter(p["registry_source_id"] for p in proposals)
    duplicate_groups_by_source = Counter(
        p["registry_source_id"] for p in proposals if p["evidence_count"] > 1
    )
    duplicate_rows_collapsed_by_source = Counter(
        {
            source: sum(
                p["evidence_count"] - 1
                for p in proposals
                if p["registry_source_id"] == source and p["evidence_count"] > 1
            )
            for source in proposals_by_source
        }
    )

    report = {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "staging_candidates_seen": len(candidates),
        "current_primary_rows_considered": sum(source_rows.values()),
        "current_primary_rows_by_source": dict(sorted(source_rows.items())),
        "identity_proposals": len(proposals),
        "identity_proposals_by_source": dict(sorted(proposals_by_source.items())),
        "singleton_proposals": sum(1 for p in proposals if p["evidence_count"] == 1),
        "ambiguous_proposals": len(review_tasks),
        "duplicate_groups_by_source": dict(sorted(duplicate_groups_by_source.items())),
        "duplicate_rows_collapsed_by_source": dict(sorted(duplicate_rows_collapsed_by_source.items())),
        "missing_identity_key_rows": sum(missing_key.values()),
        "missing_identity_key_reasons": dict(sorted(missing_key.items())),
        "ignored_rows": sum(ignored.values()),
        "ignored_reasons": dict(sorted(ignored.items())),
        "automatic_identity_acceptances": 0,
        "edu_core_rows_created": 0,
        "core_mutation_performed": False,
        "public_promotion_performed": False,
        "notes": [
            "This is an identity proposal plan, not an edu_core import.",
            "Repeated source rows may collapse into one proposal only when the source-specific deterministic key matches.",
            "All proposals remain unreviewed or needs_review; no match is accepted automatically.",
            "MOHESR and other official registries remain outside this planner until cross-registry reconciliation rules are defined.",
        ],
    }
    return proposals, review_tasks, report


def write_jsonl(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--candidates", required=True, type=Path)
    parser.add_argument("--out-dir", default="artifacts/edu-data-1/core-seed-plan", type=Path)
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    candidates = load_jsonl(args.candidates)
    proposals, review_tasks, report = build_plan(candidates)

    proposals_path = args.out_dir / "core_identity_proposals.jsonl"
    review_path = args.out_dir / "identity_review_tasks.jsonl"
    report_path = args.out_dir / "core_seed_plan_report.json"
    write_jsonl(proposals_path, proposals)
    write_jsonl(review_path, review_tasks)
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
